----
-- Author: Robert Eichler
----

insert into Permissions (Permission_id, name) values
    (1000, 'Simulierte Standortquellen für Testzwecke'),
    (1001, 'Netzwerkverbindungen abrufen'),
    (1002, 'Konten erstellen und Passwörter festlegen'),
    (1003, 'Akkudaten lesen'),
    (1004, 'mit Bluetooth-Geräten koppeln'),
    (1005, 'Auf Bluetooth-Einstellungen zugreifen'),
    (1006, 'Dauerhaften Broadcast senden'),
    (1007, 'System-Anzeigeeinstellungen ändern'),
    (1008, 'Netzwerkkonnektivität ändern'),
    (1009, 'WLAN-Multicast-Empfang zulassen'),
    (1010, 'WLAN-Verbindungen herstellen und trennen'),
    (1011, 'WiMAX-Status ändern'),
    (1012, 'Alle Cache-Daten der App löschen'),
    (1013, 'Bildschirmsperre deaktivieren'),
    (1014, 'Statusleiste ein-/ausblenden'),
    (1015, 'Lichtanzeige steuern'),
    (1016, 'Speicherplatz der App ermitteln'),
    (1017, 'Zugriff auf alle Netzwerke'),
    (1018, 'Andere Apps schließen'),
    (1019, 'Audio-Einstellungen ändern'),
    (1020, 'Nahfeldkommunikation steuern'),
    (1021, 'App permanent ausführen'),
    (1022, 'Synchronisierungseinstellungen lesen'),
    (1023, 'Begriffe lesen, die du zum Wörterbuch hinzugefügt hast'),
    (1024, 'Beim Start ausführen'),
    (1025, 'Aktive Apps neu ordnen'),
    (1026, 'Fehlerbeseitigung für App aktivieren'),
    (1027, 'Zeitzone festlegen'),
    (1028, 'Hintergrund festlegen'),
    (1029, 'Über anderen Apps einblenden'),
    (1030, 'Konten auf dem Gerät verwenden'),
    (1031, 'Vibrationsalarm steuern'),
    (1032, 'Ruhezustand deaktivieren'),
    (1033, 'Systemeinstellungen ändern'),
    (1034, 'Synchronisierung aktivieren oder deaktivieren'),
    (1035, 'Wörter zu meinem Wörterbuch hinzufügen'),
    (1036, 'Wecker stellen'),
    (1037, 'Lesezeichen für Webseiten setzen und das Webprotokoll aufzeichnen'),
    (1038, 'Verknüpfungen installieren'),
    (1039, 'Verknüpfungen deinstallieren'),
    (1040, 'Google Play-Lizenzprüfung'),
    (1041, 'Google-Servicekonfiguration lesen'),
    (1042, 'Auf das Cache-Dateisystem zugreifen'),
    (1043, 'Auf Download-Manager zugreifen'),
    (1044, 'WiMAX-Verbindungen herstellen und trennen'),
    (1045, 'Widgets auswählen'),
    (1046, 'Daten anderer Apps löschen'),
    (1047, 'Apps löschen'),
    (1048, 'Gerät ein- oder ausschalten'),
    (1049, 'Lese-/Schreibberechtigung für zur Diagnosegruppe gehörige Elemente'),
    (1050, 'Dateien ohne Benachrichtigung herunterladen'),
    (1051, 'Apps direkt installieren'),
    (1052, 'Vollständige Lizenz zum nutzerübergreifenden Interagieren'),
    (1053, 'Installationssitzungen lesen'),
    (1054, 'In sozialem Stream lesen'),
    (1055, 'Synchronisierungsstatistiken lesen'),
    (1056, 'Andere Apps schließen'),
    (1057, 'Größe des Hintergrundbildes anpassen'),
    (1058, 'Abonnierte Feeds lesen'),
    (1059, 'Abonnierte Feeds erstellen'),
    (1060, 'Infrarotübertragung'),
    (1061, 'Akku-Daten ändern'),
    (1062, 'Inhalt interner Speichermedien ändern/löschen'),
    (1063, 'Sicherheitseinstellungen für das System ändern'),
    (1064, 'In sozialem Stream schreiben'),
    (1065, 'Einstellungen und Verknüpfungen auf dem Startbildschirm lesen'),
    (1066, 'Einstellungen und Verknüpfungen für den Startbildschirm schreiben'),
    (1067, 'Daten aus dem Internet abrufen'),
    (1068, 'Konfigurierte Konten abrufen'),
    (1069, 'Auf weitere Google-Dienste zugreifen'),
    (1070, 'YouTube-Nutzernamen'),
    (1071, 'AdSense'),
    (1072, 'AdWords'),
    (1073, 'Google App Engine'),
    (1074, 'Blogger'),
    (1075, 'Google Kalender'),
    (1076, 'Kontaktdaten in Google-Konten'),
    (1077, 'Dodgeball'),
    (1078, 'Google Finanzen'),
    (1079, 'Google Base'),
    (1080, 'Google Voice'),
    (1081, 'Google Groups'),
    (1082, 'Google Gesundheit'),
    (1083, 'iGoogle-Konten'),
    (1084, 'JotSpot'),
    (1085, 'Knol'),
    (1086, 'Picasa-Webalben'),
    (1087, 'Google Maps'),
    (1088, 'Google Mail'),
    (1089, 'Google Mobile Apps'),
    (1090, 'Google News'),
    (1091, 'Google Notizbuch'),
    (1092, 'orkut'),
    (1093, 'Google Books'),
    (1094, 'Google Search Console'),
    (1095, 'Google Sprachsuche'),
    (1096, 'Personalisierte Spracherkennung'),
    (1097, 'Google Talk'),
    (1098, 'Google WiFi'),
    (1099, 'Google Tabellen'),
    (1100, 'Google Docs'),
    (1101, 'YouTube'),
    (1102, 'Chatnachrichten lesen'),
    (1103, 'Chatnachrichten schreiben');
